---
abstract: 'Send mails due to a F<birthday.json> file and a given'
author:
  - 'Farhad Fouladi <farhad@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-Birthday
no_index:
  directory:
    - t
    - inc
requires:
  Getopt::Std: 0
  JSON::PP: 0
  Mail::Sender: 0
  Test::More: 0
version: 0.1
